title: Minimal theme
logo: https://github.com/bhushan707/minimal/blob/master/assets/img/WhatsApp%20Image%202022-03-28%20at%2010.48.36%20AM.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
